language: java

dist: trusty

addons:
  sonarcloud:
    organization: antop-dev-github

jdk:
  - openjdk8

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.m2

script:
  - mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn clean verify jacoco:report
  - mvn sonar:sonar -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.projectKey=$SONAR_PROJECT_KEY

notifications:
  email: false
