# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST http://localhost:8012/xmlrpc
Content-Type: text/xml

<?xml version="1.0" encoding="UTF-8"?>
<methodCall xmlns:ex="http://ws.apache.org/xmlrpc/namespaces/extensions">
    <methodName>Appointment.openSlotRequest</methodName>
    <params>
        <param>
            <value>
                <ex:serializable>rO0ABXNyAA1qYXZhLnRpbWUuU2VylV2EuhsiSLIMAAB4cHcHAwAAB+MKFHg=</ex:serializable>
            </value>
        </param>
        <param>
            <value>mjones</value>
        </param>
    </params>
</methodCall>

###

POST http://localhost:8012/xmlrpc
Content-Type: text/xml

<?xml version="1.0" encoding="UTF-8"?>
<methodCall xmlns:ex="http://ws.apache.org/xmlrpc/namespaces/extensions">
    <methodName>org.antop.xmlrpc.service.AppointmentService.appointmentRequest</methodName>
    <params>
        <param>
            <value>
                <ex:serializable>
                    rO0ABXNyABtvcmcuYW50b3AueG1scnBjLm1vZGVsLlNsb3SKqAx35vVeQwIAA0wABmRvY3RvcnQAEkxqYXZhL2xhbmcvU3RyaW5nO0wAA2VuZHQAFUxqYXZhL3RpbWUvTG9jYWxUaW1lO0wABXN0YXJ0cQB+AAJ4cHQABm1qb25lc3NyAA1qYXZhLnRpbWUuU2VylV2EuhsiSLIMAAB4cHcDBBDNeHNxAH4ABXcCBO94
                </ex:serializable>
            </value>
        </param>
        <param>
            <value>
                <ex:serializable>
                    rO0ABXNyAB5vcmcuYW50b3AueG1scnBjLm1vZGVsLlBhdGllbnTemVxtdsaxqAIAAUwAAmlkdAASTGphdmEvbGFuZy9TdHJpbmc7eHB0AAZqc21pdGg=
                </ex:serializable>
            </value>
        </param>
    </params>
</methodCall>

###

POST http://localhost:8012/xmlrpc
Content-Type: text/xml

<?xml version="1.0" encoding="UTF-8"?>
<methodCall xmlns:ex="http://ws.apache.org/xmlrpc/namespaces/extensions">
    <methodName>org.antop.xmlrpc.service.AppointmentService.appointmentRequest</methodName>
    <params>
        <param>
            <value>
                <ex:serializable>
                    rO0ABXNyABtvcmcuYW50b3AueG1scnBjLm1vZGVsLlNsb3SKqAx35vVeQwIAA0wABmRvY3RvcnQAEkxqYXZhL2xhbmcvU3RyaW5nO0wAA2VuZHQAFUxqYXZhL3RpbWUvTG9jYWxUaW1lO0wABXN0YXJ0cQB+AAJ4cHQABWFudG9wc3IADWphdmEudGltZS5TZXKVXYS6GyJIsgwAAHhwdwMEEM14c3EAfgAFdwIE73g=
                </ex:serializable>
            </value>
        </param>
        <param>
            <value>
                <ex:serializable>
                    rO0ABXNyAB5vcmcuYW50b3AueG1scnBjLm1vZGVsLlBhdGllbnTemVxtdsaxqAIAAUwAAmlkdAASTGphdmEvbGFuZy9TdHJpbmc7eHB0AAZqc21pdGg=
                </ex:serializable>
            </value>
        </param>
    </params>
</methodCall>

###